name:                tdouble3
version:             0.1.0.0
github:              "githubuser/tdouble3"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md
- src/TDouble.hsc

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/tdouble3#readme>

dependencies:
- base >= 4.7 && < 5
- haskell-gi-base
- gi-gobject
- bytestring

library:
  source-dirs: src
  verbatim:
    default-language: GHC2021

executables:
  tdouble3:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tdouble3
    verbatim:
      default-language: GHC2021

tests:
  tdouble3-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - tdouble3
    verbatim:
      default-language: GHC2021